sonar.projectKey=kessie12_asc-inventory-management-system
sonar.organization=kessie12


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=asc-inventory-management-system
sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Disable the Oracle PL/SQL analyzer entirely to prevent the Data Dictionary warning
sonar.plsql.file.suffixes=-

# This requires Xdebug or PCOV installed on your PHP environment
vendor/bin/phpunit --coverage-clover phpunit.coverage.xml

# Exclude all PHP files from code coverage requirements
sonar.coverage.exclusions=**/*.php

# Exclude vendor folder from all analysis (bugs, vulnerabilities, etc.)
sonar.exclusions=vendor/**, **/*.sql, **/*.pks, **/*.pkb

# If you ONLY want to exclude specific folders from the duplication check, use this:
sonar.exclusions=**/*.sql, **/*.pks, **/*.pkb

# Ignore specific folders from the duplication check
sonar.exclusions=vendor/**, model/**, **/*.sql, **/*.pks, **/*.pkb

sonar.cpd.exclusions=vendor/**, model/**
